export const ServiceInHomeData = [
  {
    text: "Clipping Path",
    defaultClass: "bg_red",
    imgSource: "/home/product-1-red-shoe_255x192.png",
    des: "Removing the backgrounds of an image can be extremely monotonous. Most e-commerce companies prefer images with white backgrounds. By having the Background Removal service, we can have all backgrounds of the images removed effortlessly.",
    destination: "",
  },
  {
    text: "Background Removal",
    defaultClass: "bg_blue",
    imgSource: "/home/product-8_255x192.png",
    des: "Removing the backgrounds of an image can be extremely monotonous. Most e-commerce companies prefer images with white backgrounds. By having the Background Removal service, we can have all backgrounds of the images removed effortlessly.",
    destination: "",
  },
  {
    text: "Image Masking",
    defaultClass: "bg_red",
    imgSource: "/home/product-9_255x192.png",
    des: "When working with hairs, brush type or furry items, and sharp edges, image masking is the only way to give them details. On these types of items the clipping path feature typically doesn’t work. By availing our image masking service you can make the products look like a charm.        ",
    destination: "",
  },
  {
    text: "Shadow",
    defaultClass: "bg_beguni",
    imgSource: "/home/product-10_255x192.png",
    des: "Shadows give a good vibe to your image and make you think you can hold the product right now. One-dimensional shadows won’t be enough, though. We set multiple layers of shadow to make a product look attractive. So, keep faith in Photoeditzone.",
    destination: "",
  },
  {
    text: "Ghost Mannequin",
    defaultClass: "bg_yellow",
    imgSource: "/home/product-3_255x192.png",
    des: "If you can make the customer imagine how’d they look if they wear the t-shirt or sweater they are looking at. You can bet that your sales rate will increase.That’s where our Ghost Mannequin service comes into play. This service works as a substitute for plastic live models. ",
    destination: "",
  },
  {
    text: "Color Change",
    defaultClass: "bg_beguni",
    imgSource: "/home/product-11_255x192.png",
    des: "It’s always a good idea to give multiple color options to customers. The more color a product has the more attractive the product becomes.Another thing is why would you take pictures of the same product 10 times if it does come with 10 colors, right? With the color changing feature, we can capture the image of a product one time and change the color later according to your need.",
    destination: "",
  },
  {
    text: "Photo Retouching",
    defaultClass: "bg_yellow",
    imgSource: "/home/product-camera-yellow_255x192.png",
    des: "Being a perfectionist is never wrong. Your camera may not always capture the perfect photo of your product. But the thing is, it doesn’t need to anymore. With the Photo Retouching feature, we will get the look and feel of a picture exactly how you want. ",
    destination: "",
  },
  {
    text: "Multi-clipping Path",
    defaultClass: "bg_red",
    imgSource: "/home/product-bicycle-red_255x192.png",
    des: "If you want to make your products stand out, you need to take some complex measures like Multi-clipping Path. Multi-clipping can get extremely tough, not only that, it may consume a lot of time and money as well. That’s where the Multi-clipping Path comes in. To ensure a perfect clipping path Photoeditzone doesn’t use automated tools. Instead, we do this work by hand so you’ll get details like never before. ",
    destination: "",
  },
  {
    text: "Vector Conversion",
    defaultClass: "bg_blue",
    imgSource: "/home/service-vector-service-header_255x192.png",
    des: "Consider the possibility that you want to keep a certain picture to use it later as a logo, banner or T-shirt prints. What will be your call then? That’s when you will need to use our Vector Conversion service. A normal picture will get blurry or lose the details when stretching or enlarging it. But if you preserve that certain file in vector form. You can make changes to the picture whenever you want. ",
    destination: "",
  },
];
